### ISSUE TITLE
기초통계&회귀분석

### ISSUE THREAD

**Issue by Treeboy2762** [kimsh0507/session_assignment#1]
안녕하세요, 가설검정에서 표본 수를 구하실 때

n_x = X.size 를 사용하셨는데, 이는 df 의 cell 숫자 (32 rows * 12 columns = 384) 를 반환하게 됩니다.

len(X) 를 권장드립니다. 수고 많으셨습니다~

확인하시고 close issue 부탁드립니다

**Comment by kimsh0507** [comment]
감사합니다!
